version: "3"

networks: 
  static_tributePage_nginx:
    driver: bridge

services:
  # nginx web proxy
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80" # expose 80 on host and sent to 80 in container
    networks:
      - static_tributePage_nginx
    restart: always
    volumes:
      - ./library:/usr/share/nginx/html/library
